version: '3.8'

services:
  sample-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"